import React from "react"; 
import { Inter } from "next/font/google"; 
import { ClerkProvider } from "@clerk/nextjs"; // Import ClerkProvider for user authentication

import "../globals.css"; 
export const metadata = {
  title: "Auth",
  description: "Generated by create next app", 
}

const inter = Inter({ subsets: ["latin"] }); // Create an instance of the Inter font with Latin subset

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      {" "}
      {/* Render ClerkProvider to enable user authentication via Clerk */}
      <html lang="en">
        {" "}
       
        <body className={`${inter.className} bg-dark-1`}>
         
          <div className="w-full flex justify-center items-center min-h-screen">
            {children} 
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
